bathy_snr_min: 3
cc: null
debug: false
input_file: local/Oahu/ICESat2/Oahu_icesat2_atl03.parquet
kde_surf_method: isj
make_plots: 1
max_gap_bins_m: 100
method_nonsurf_bins: n
method_surface_bins: n
min_data_nonsurface: 25
min_data_surface: 50
n_nodes: 6
n_ph_nonsurf_bins: 100
n_ph_surface_bins: 10000
output_dir: local/Oahu/run_mod_output
overlap_nonsurf: 0.9
overlap_surface: 0.5
profile_limit: null
request_name: Oahu
rgt: null
serial: false
spot: null
surf_sigma_cutoff: 5
x_m_nonsurf_bins: 50
x_m_surface_bins: 100
